apiVersion: v1
kind: Pod
metadata:
  generateName: burstable-
spec:
  containers:
  - image: busybox
    name: busybox
    command:
    - sleep
    - "3600"
    resources:
      requests:
        memory: 1500Mi
        cpu: 300m
      limits:
        cpu: 1
        memory: 3Gi
  restartPolicy: Always
  terminationGracePeriodSeconds: 0
