apiVersion: v1
kind: Pod
metadata:
  generateName: liveness-
spec:
  containers:
  - image: busybox
    name: busybox
    command:
    - sleep
    - "3600"
    resources:
      requests:
        memory: 1500Mi
        cpu: 300m
    livenessProbe:
      httpGet:
        path: /dancertestt
        port: 3000
        scheme: HTTP
      initialDelaySeconds: 30
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 5                                
  restartPolicy: Always
  terminationGracePeriodSeconds: 0
