apiVersion: v1
kind: Pod
metadata:
  generateName: test-
spec:
  containers:
  - image: docker.io/sjenning/malloc:latest
    name: malloc
    command:
    - "/malloc"
    - "2500"
    imagePullPolicy: Always
    resources:
      limits:
        memory: 100Mi
      requests:
        memory: 100Mi  
  restartPolicy: Always
  terminationGracePeriodSeconds: 0
