apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  containers:
  - image: busybox
    name: busybox1
    command:
    - sleep
    - "3600"
    resources:
      requests:
        memory: 1500Mi
        cpu: 300m
  - image: busybox
    name: busybox2
    command:
    - sleep
    - "3600"
    resources:
      requests:
        memory: 1500Mi
        cpu: 300m        
  restartPolicy: Always
  terminationGracePeriodSeconds: 0
