apiVersion: v1
kind: Pod
metadata:
  generateName: test-pd
spec:
  restartPolicy: Never
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      medium: Memory
